### ISSUE TITLE
Make Pale Moon application specific code buildable

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Tycho#23]
Blocks #22 

Buildability Status:
- [X] Windows
- [X] Linux
- [ ] Mac

**Comment by mattatobin** [comment]
RESOLVED FIXED

**Comment by mattatobin** [comment]
Actually this should stay open until Travis has managed evaluate and fix things on Linux

**Comment by trav90** [comment]
No go on Linux yet (although this build failure could to be related to commits d30f5a5 & d33cc37).

Build log: https://gist.github.com/trav90/20e15131f3a71b51f58a59bd8bf8a2b8

**Comment by trav90** [comment]
Build still fails on Linux. GCC throws tons of warning in ICU, before failing in gfx/graphite2. Full build log:

https://gist.github.com/trav90/26c379f36b83da7bbfe7053d609072fb

**Comment by wolfbeast** [comment]
It errors in third-party code... Not sure why; maybe unified building graphite2 doesn't work so well on gcc.

**Comment by trav90** [comment]
Yes, but Tycho built fine on Linux at commit b00f3ff. I don't see any changes to third party code since then, so I don't know why it's failing at that point now.

**Comment by trav90** [comment]
An update: Turns out Manjaro recently updated system GCC to version 6.1.1, which appears to be incompatible. Going to kick off another build using 4.9 and report back.

**Comment by trav90** [comment]
Linux build completes successfully with GCC 4.9. RESOLVED FIXED for Linux as well.

**Comment by mattatobin** [comment]
Mac building would need to be tested next.. But I suspect mac packaging is gonna be all KINDS of screwed up.. Someone needs to poke the mac person. (I don't have my infra setup to do mac yet but would like to know of the results of an attempt)

**Comment by trav90** [comment]
@stevenschlansker, could you give this a try?

**Comment by stevenschlansker** [comment]
Yes, I can give this a try this week.

**Comment by stevenschlansker** [comment]
```
 3:19.81 /Users/pale/jenkins/workspace/tycho/default/browser/components/shell/nsMacShellService.cpp:35:1: error: static_assert failed "Reference-counted class nsMacShellService should not have a public destructor. Try to make this class's destructor non-public. If that is really not possible, you can whitelist this class by providing a HasDangerousPublicDestructor specialization for it."
 3:19.84 NS_IMPL_ISUPPORTS(nsMacShellService, nsIMacShellService, nsIShellService, nsIWebProgressListener)
 3:19.84 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3:19.85 ../../../dist/include/nsISupportsImpl.h:1030:3: note: expanded from macro 'NS_IMPL_ISUPPORTS'
 3:19.85   NS_IMPL_ADDREF(aClass)                                                      \
 3:19.85   ^~~~~~~~~~~~~~~~~~~~~~
 3:19.87 ../../../dist/include/nsISupportsImpl.h:564:3: note: expanded from macro 'NS_IMPL_ADDREF'
 3:19.87   MOZ_ASSERT_TYPE_OK_FOR_REFCOUNTING(_class)                                  \
 3:19.87   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3:19.87 ../../../dist/include/nsISupportsImpl.h:91:3: note: expanded from macro 'MOZ_ASSERT_TYPE_OK_FOR_REFCOUNTING'
 3:19.88   static_assert(!MOZ_IS_DESTRUCTIBLE(X) || \
 3:19.88   ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3:20.44 /Users/pale/jenkins/workspace/tycho/default/browser/components/shell/nsMacShellService.cpp:206:51: error: too few arguments to function call, expected 8, have 7
 3:20.45                       mBackgroundFile, loadContext);
 3:20.45                                                   ^
 3:20.52 ../../../dist/include/nsIWebBrowserPersist.h:86:3: note: 'SaveURI' declared here
 3:20.53   NS_IMETHOD SaveURI(nsIURI *aURI, nsISupports *aCacheKey, nsIURI *aReferrer, uint32_t aReferrerPolicy, nsIInputStream *aPostData, const char * aExtraHeaders, nsISupports *aFile, nsILoadContext *aPrivacyContext) = 0;
 3:20.53   ^
 3:20.53 ../../../dist/include/nscore.h:185:29: note: expanded from macro 'NS_IMETHOD'
 3:20.54 #define NS_IMETHOD          NS_IMETHOD_(nsresult)
 3:20.54                             ^
 3:20.55 ../../../dist/include/nscore.h:123:27: note: expanded from macro 'NS_IMETHOD_'
 3:20.55 #define NS_IMETHOD_(type) virtual type
 3:20.55                           ^
 3:20.60 /Users/pale/jenkins/workspace/tycho/default/browser/components/shell/nsMacShellService.cpp:230:20: error: out-of-line definition of 'OnStatusChange' does not match any declaration in 'nsMacShellService'
 3:20.61 nsMacShellService::OnStatusChange(nsIWebProgress* aWebProgress,
 3:20.61                    ^~~~~~~~~~~~~~
 3:21.17 3 errors generated.
```

That's where I get to for now.

**Comment by wolfbeast** [comment]
The error message (see line 1) is very descriptive for a change. See if you can change nsMacShellService accordingly?

**Comment by mattatobin** [comment]
nsMacShellService.. Should have known..

Check for major differences between:

https://github.com/MoonchildProductions/Tycho/blob/7dcb42f8341ff1645326b5c2948330e38e979bc4/browser/components/shell/nsMacShellService.cpp
https://github.com/MoonchildProductions/Tycho/blob/7dcb42f8341ff1645326b5c2948330e38e979bc4/browser/components/shell/nsMacShellService.h

with what is on trunk.

**Comment by mattatobin** [comment]
Mac building RESOLVED FIXED in PR #47 and #49

**Comment by mattatobin** [comment]
@stevenschlansker can you please give us a status update on the buildablity on mac.. It does not have to include packaging because we are dealing with packaging in a separate bug.

**Comment by stevenschlansker** [comment]
The build completes successfully, but packaging fails: #54

**Comment by wolfbeast** [comment]
De-coupling the packaging issue on Mac from this bug so this can be marked solved -- it's buildable after all which is a larger issue than some scripting for packaging.

**Comment by stevenschlansker** [comment]
#61 turns out to still be required to fix the Mac build, but broke Windows build.  So we still have to figure out a solution to that before all the builds are truly fixed.  I'll try to take another look at it later this week.
